# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang
  - gcc

# Install dependencies
addons:
  apt:
    packages:
      - libboost-all-dev
      - libdb5.1-dev
      - libdb5.1++-dev
      - libminiupnpc-dev
      - libssl-dev
      - qt5-default
      - qt5-qmake
      - qtbase5-dev-tools
      - qttools5-dev-tools
      - libqrencode-dev

before_install:
  # Clang is not system wide.  This is a work around.
  - $CC --version
  - which $CC
  - export CC=`which $CC`

# Build steps
script:
  - cd src/secp256k1/
  - chmod +x ./autogen.sh
  - ./autogen.sh
  - ./configure -prefix=/usr
  - sudo make install
  - cd ../../
  - qmake USE_QRCODE=1 "QMAKE_CXX=$CXX" "QMAKE_CC=$CC"
  - make clean
  - make
  - cd src
  - make -f makefile.unix clean
  - make -f makefile.unix
